#!/usr/bin/env bash
set -euo pipefail

check_os() {
  OS="$(uname)"
  case "$OS" in
    'Darwin')
      OS='Mac'
      ;;
    'Linux')
      OS='Linux'
      ;;
    *)
      echo "Unsupported OS: $OS"
      exit 1
      ;;
  esac
  echo "$OS"
}

install_package() {
  package=$1
  if [ "$OS" == "Mac" ]; then
    gum spin --spinner line --title "Installing $package" -- brew install "$package"
  elif [ "$OS" == "Linux" ]; then
    gum spin --spinner line --title "Installing $package" -- sudo apt-get install "$package"
  fi
  echo "[$(pprint ✓)] $package"
}

pprint() {
  gum style --foreground 212 "$@"
}

checkmark() {
  echo "[$(pprint ✓)] $@"
}

bootstrap() {
  echo "Running on $OS. Bootstrapping..."
  echo
  if [ "$OS" == "Mac" ]; then
    brew -v &> /dev/null || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    (echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> ~/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"
    brew install gum &> /dev/null 
    checkmark "homebrew"
    checkmark "gum"
  else
    echo "Linux support coming soon!"
  fi
}

clone_ansible_repo() {
  if [ ! -d ~/personal/ansible ]; then
    gum spin --spinner line --title "Cloning ansible repo" -- git clone https://github.com/barlevalon/ansible ~/personal/ansible
    checkmark "ansible repo"
  fi
}

run_ansible() {
  cd ~/personal/ansible
  gum spin --spinner line --title "Installing ansible dependencies" -- ansible-galaxy install -r requirements.yaml
  checkmark "ansible dependencies"
  gum spin --spinner line --title "Running ansible" --show-output -- ansible-playbook -K playbook.yaml
}

# Main
OS=$(check_os)
bootstrap
install_package ansible
clone_ansible_repo
run_ansible
echo
checkmark "Done!"
