---
homebrew_cask_apps:
  - arc
  - google-drive
  - 1password
  - 1password-cli
  - kitty
  - odrive
  - logseq
  - vlc
  - adobe-acrobat-reader
  - adobe-creative-cloud
  - raycast

homebrew_installed_packages:
  - coreutils
  - mas
  - gcc
  - koekeishiya/formulae/skhd
  - yabai
  - stow
  - nvim
  - git
  - gh
  - lazygit
  - bat
  - btop
  - colima
  - docker
  - exa
  - fd
  - ripgrep
  - erdtree
  - fish
  - tmux
  - starship
  - fzf
  - jq
  - make
  - fnm
  - go
  - kubernetes-cli
  - k9s
  - terraform
  - helm
  - awscli
  - argocd
  - busser/tap/tfautomv
  - syncthing
  - tealdeer
  - urlview
