- hosts: localhost

  var_files:
    - config.yaml

  roles:
    - macos
    - fonts
    - dotfiles
    - geerlingguy.mac.homebrew

  tasks:
    - name: Create ~/personal
      file:
        path: ~/personal
        state: directory

    - name: Create ~/work
      file:
        path: ~/work
        state: directory

    - name: Clone ansible repo
      git:
        repo: https://github.com/barlevalon/ansible
        update: false
        dest: ~/personal/ansible

    - name: yabai service
      command: yabai --start-service
      args:
        creates: ~/Library/LaunchAgents/com.koekeishiya.yabai.plist
    
    - name: skhd service
      command: skhd --start-service
      args:
        creates: ~/Library/LaunchAgents/com.koekeishiya.skhd.plist

    - name: syncthing service
      command: brew services start syncthing
      args:
        creates: ~/Library/LaunchAgents/homebrew.mxcl.syncthing.plist
    
    - name: omf
      shell: |
        curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install > install
        fish install --yes --noninteractive --path=~/.local/share/omf --config=~/.config/omf 
      args:
        creates: ~/.local/share/omf/

    - name: gh-dash
      command: gh extension install dlvhdr/gh-dash
      args:
        creates: ~/.local/share/gh/extensions/gh-dash/gh-dash
