- hosts: localhost
  vars:
    brew_casks:
      - arc
      - google-drive
      - 1password
      - 1password-cli
      - kitty
      - odrive
      - logseq
      - vlc
      - adobe-acrobat-reader
      - adobe-creative-cloud
      - raycast
    brew_packages:
      - coreutils
      - mas
      - gcc
      - koekeishiya/formulae/skhd
      - yabai
      - stow
      - nvim
      - git
      - gh
      - lazygit
      - bat
      - btop
      - colima
      - docker
      - exa
      - fd
      - ripgrep
      - erdtree
      - fish
      - tmux
      - starship
      - fzf
      - jq
      - make
      - fnm
      - go
      - kubernetes-cli
      - k9s
      - terraform
      - helm
      - awscli
      - argocd
      - busser/tap/tfautomv
      - syncthing
      - tealdeer
      - urlview
    fonts:
      - font-3270-nerd-font
      - font-agave-nerd-font
      - font-anonymice-nerd-font
      - font-arimo-nerd-font
      - font-aurulent-sans-mono-nerd-font
      - font-bigblue-terminal-nerd-font
      - font-bitstream-vera-sans-mono-nerd-font
      - font-blex-mono-nerd-font
      - font-caskaydia-cove-nerd-font
      - font-code-new-roman-nerd-font
      - font-cousine-nerd-font
      - font-daddy-time-mono-nerd-font
      - font-dejavu-sans-mono-nerd-font
      - font-droid-sans-mono-nerd-font
      - font-fantasque-sans-mono-nerd-font
      - font-fira-code
      - font-fira-code-nerd-font
      - font-fira-mono-nerd-font
      - font-go-mono-nerd-font
      - font-gohufont-nerd-font
      - font-hack-nerd-font
      - font-hasklug-nerd-font
      - font-heavy-data-nerd-font
      - font-hurmit-nerd-font
      - font-im-writing-nerd-font
      - font-inconsolata-go-nerd-font
      - font-inconsolata-lgc-nerd-font
      - font-inconsolata-nerd-font
      - font-iosevka-nerd-font
      - font-jetbrains-mono-nerd-font
      - font-lekton-nerd-font
      - font-liberation-nerd-font
      - font-meslo-lg-nerd-font
      - font-monofur-nerd-font
      - font-monoid-nerd-font
      - font-mononoki-nerd-font
      - font-mplus-nerd-font
      - font-noto-nerd-font
      - font-open-dyslexic-nerd-font
      - font-overpass-nerd-font
      - font-profont-nerd-font
      - font-proggy-clean-tt-nerd-font
      - font-roboto-mono-nerd-font
      - font-sauce-code-pro-nerd-font
      - font-shure-tech-mono-nerd-font
      - font-space-mono-nerd-font
      - font-terminess-ttf-nerd-font
      - font-tinos-nerd-font
      - font-ubuntu-mono-nerd-font
      - font-ubuntu-nerd-font
      - font-victor-mono
      - font-victor-mono-nerd-font
  tasks:
    - name: Create ~/personal
      file:
        path: ~/personal
        state: directory

    - name: Create ~/work
      file:
        path: ~/work
        state: directory

    - name: Clone dotfiles
      git:
        repo: https://github.com/barlevalon/dotfiles
        update: false
        dest: ~/dotfiles

    - name: Clone ansible repo
      git:
        repo: https://github.com/barlevalon/ansible
        update: false
        dest: ~/personal/ansible

    - name: stow dotfiles
      shell: make
      args:
        chdir: ~/dotfiles

    - name: Install rosetta
      shell: /usr/sbin/softwareupdate --install-rosetta --agree-to-license
      when: ansible_facts['os_family'] == "Darwin"
      args:
        creates: /usr/libexec/rosetta/oahd

    - name: MacOS Defaults
      shell: |
        defaults write com.apple.dock autohide -bool true
        defaults write com.apple.dock show-recents -bool false
        defaults write com.apple.dock mru-spaces -bool false
        killall Dock
        defaults write -g InitialKeyRepeat -int 12
        defaults write -g KeyRepeat -int 1
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install brew casks
      homebrew_cask:
        update_homebrew: true
        name: "{{ brew_casks }}"
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install brew packages
      homebrew:
        update_homebrew: true
        name: "{{ brew_packages }}"
      when: ansible_facts['os_family'] == "Darwin"

    - name: Brew tap fonts
      homebrew_tap:
        name: homebrew/cask-fonts

    - name: Install fonts
      homebrew_cask:
        update_homebrew: true
        name: "{{ fonts }}"
      when: ansible_facts['os_family'] == "Darwin"

      # syncthing service
    - name: yabai service
      command: yabai --start-service
      args:
        creates: ~/Library/LaunchAgents/com.koekeishiya.yabai.plist
    
    - name: skhd service
      command: skhd --start-service
      args:
        creates: ~/Library/LaunchAgents/com.koekeishiya.skhd.plist

    - name: syncthing service
      command: brew services start syncthing
      args:
        creates: ~/Library/LaunchAgents/homebrew.mxcl.syncthing.plist
    
    - name: omf
      shell: |
        curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install > install
        fish install --yes --noninteractive --path=~/.local/share/omf --config=~/.config/omf 
      args:
        creates: ~/.local/share/omf/

    - name: gh-dash
      command: gh extension install dlvhdr/gh-dash
      args:
        creates: ~/.local/share/gh/extensions/gh-dash/gh-dash
