- hosts: localhost
  vars:
    brew_casks:
      - arc
      - google-drive
      - 1password
      - 1password-cli
      - kitty
      # - odrive
      - logseq
      - vlc
      - adobe-acrobat-reader
      - adobe-creative-cloud
      - raycast
    brew_packages:
      - coreutils
      - mas
      - gcc
      - koekeishiya/formulae/skhd
      - yabai
      - stow
      - nvim
      - git
      - lazygit
      - bat
      - btop
      - colima
      - docker
      - exa
      - fd
      - ripgrep
      - erdtree
      - fish
      - tmux
      - starship
      - fzf
      - jq
      - make
      - fnm
      - go
      - kubernetes-cli
      - k9s
      - terraform
      - helm
      - awscli
      - argocd
      - tfautomv
      - syncthing
      - tealdeer
  tasks:
    - name: Install rosetta
      shell: /usr/sbin/softwareupdate --install-rosetta --agree-to-license
    - name: Install brew casks
      homebrew_cask:
        update_homebrew: true
        name: "{{ brew_casks }}"
      when: ansible_facts['os_family'] == "Darwin"

    - name: Install brew packages
      homebrew:
        update_homebrew: true
        name: "{{ brew_packages }}"
      when: ansible_facts['os_family'] == "Darwin"

    - name: Clone dotfiles
      git:
        repo: https://github.com/barlevalon/dotfiles
        update: false
        dest: ~/dotfiles

    - name: stow dotfiles
      shell: make
      args:
        chdir: ~/dotfiles
