- name: MacOS Defaults
  shell: |
    defaults write com.apple.dock autohide -bool true
    defaults write com.apple.dock show-recents -bool false
    defaults write com.apple.dock mru-spaces -bool false
    killall Dock
    defaults write -g InitialKeyRepeat -int 11
    defaults write -g KeyRepeat -int 1
  when: ansible_facts['os_family'] == "Darwin"

# Required for odrive
- name: Install rosetta
  shell: /usr/sbin/softwareupdate --install-rosetta --agree-to-license
  when: ansible_facts['os_family'] == "Darwin"
  args:
    creates: /Library/Apple/usr/libexec/rosetta/oahd

