# Required for odrive
- name: Install rosetta
  shell: /usr/sbin/softwareupdate --install-rosetta --agree-to-license
  when: ansible_facts['os_family'] == "Darwin"
  args:
    creates: /Library/Apple/usr/libexec/rosetta/oahd

- name: Install brew casks
  homebrew_cask:
    update_homebrew: true
    name: "{{ brew_casks }}"
  when: ansible_facts['os_family'] == "Darwin"

