name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3

      - name: faketty
        uses: Yuri6037/Action-FakeTTY@v1.1

      - name: Run bootstrap script
        run: faketty ./bootstrap.sh
